name: Build R1 Light Edition OS

on:
  workflow_dispatch:

jobs:
  build-os:
    runs-on: ubuntu-latest

    steps:
    # हमने गिटहब का डिप्रिकेटेड टूल हटाकर सीधे गिट क्लोन मार दिया ताकि एरर की छुट्टी हो जाए
    - name: Clone Source Code Manually
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.ref_name }}

    - name: Install System Compilers and Tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y bc build-essential libncurses-dev libssl-dev libelf-dev xorriso mtools squashfs-tools wget curl git
        sudo apt-get install -y grub-pc-bin grub-efi-amd64 -y

    - name: Run Master Ibut OS Core Build
      run: |
        echo "Starting complete core build script..."
        chmod +x build_ibut_os.sh
        ./build_ibut_os.sh

    - name: Create Hybrid Bootable ISO (Legacy MBR + UEFI Fix)
      run: |
        echo "Generating Bootable ISO File..."
        grub-mkrescue -o r1_light_edition.iso iso_root/ \
          --modules="biosdisk part_msdos part_gpt fat ext2 normal chain boot env" \
          -d /usr/lib/grub/i386-pc

    - name: Upload Finished Full Ibut OS ISO
      uses: actions/upload-artifact@v4
      with:
        name: IBUT-OS-R1-PREMIUM
        path: r1_light_edition.iso
